2021-09-13 19:19:20,975 INFO    MainThread:86049 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_init.py:_log_setup():342] Logging user logs to /Users/wenxuanzhang/Desktop/ACL_OSAKA/wandb/run-20210913_191920-2qft0qc8/logs/debug.log
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_init.py:_log_setup():343] Logging internal logs to /Users/wenxuanzhang/Desktop/ACL_OSAKA/wandb/run-20210913_191920-2qft0qc8/logs/debug-internal.log
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 3tq4ejpx
2021-09-13 19:19:20,976 INFO    MainThread:86049 [wandb_run.py:finish():1271] finishing run wxzhang0210/uncategorized/3tq4ejpx
2021-09-13 19:19:20,976 INFO    MainThread:86049 [jupyter.py:save_history():353] not saving jupyter history
2021-09-13 19:19:20,977 INFO    MainThread:86049 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-13 19:19:20,977 INFO    MainThread:86049 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-13 19:19:20,977 INFO    MainThread:86049 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-13 19:19:20,977 INFO    MainThread:86049 [wandb_run.py:_restore():1543] restore
2021-09-13 19:19:21,627 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 493
}

2021-09-13 19:19:22,140 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 493
}

2021-09-13 19:19:23,041 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,147 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,253 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,361 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,468 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,572 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,675 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 493
  total_bytes: 14274
}

2021-09-13 19:19:23,784 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:23,891 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:23,999 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:24,111 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:24,219 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:24,567 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:24,675 INFO    MainThread:86049 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14274
  total_bytes: 14274
}

2021-09-13 19:19:25,782 INFO    MainThread:86049 [wandb_run.py:_show_files():1915] logging synced files
2021-09-13 19:19:25,784 INFO    MainThread:86049 [wandb_init.py:init():424] starting backend
2021-09-13 19:19:25,784 INFO    MainThread:86049 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-13 19:19:25,786 INFO    MainThread:86049 [backend.py:ensure_launched():135] starting backend process...
2021-09-13 19:19:25,793 INFO    MainThread:86049 [backend.py:ensure_launched():140] started backend process with pid: 86587
2021-09-13 19:19:25,795 INFO    MainThread:86049 [wandb_init.py:init():429] backend started and connected
2021-09-13 19:19:25,797 INFO    MainThread:86049 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-13 19:19:25,797 INFO    MainThread:86049 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-13 19:19:25,797 INFO    MainThread:86049 [wandb_init.py:init():477] updated telemetry
2021-09-13 19:19:25,797 INFO    MainThread:86049 [wandb_init.py:init():500] communicating current version
2021-09-13 19:19:26,866 INFO    MainThread:86049 [wandb_init.py:init():505] got version response 
2021-09-13 19:19:26,866 INFO    MainThread:86049 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-13 19:19:27,434 INFO    MainThread:86049 [wandb_init.py:init():540] starting run threads in backend
2021-09-13 19:19:29,435 INFO    MainThread:86049 [wandb_run.py:_console_start():1601] atexit reg
2021-09-13 19:19:29,435 INFO    MainThread:86049 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-13 19:19:29,435 INFO    MainThread:86049 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-13 19:19:29,436 INFO    MainThread:86049 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-13 19:19:29,436 INFO    MainThread:86049 [wandb_init.py:init():565] run started, returning control to user process
2021-09-13 19:19:29,437 INFO    MainThread:86049 [wandb_run.py:_config_callback():843] config_cb None None {'dataset': 'sinusoid', 'wandb': False, 'wandb_project': None, 'wandb_name': None, 'wandb_key': None, 'num_ways': 5, 'num_shots': 5, 'num_shots_test': 15, 'num_domains': 3, 'seed': 100, 'model_name': 'ACL', 'model_name_impv': 'ACL', 'hidden_size': 8, 's_units': 16, 'd_units': 16, 's_layers': 0, 'lam': 1, 'batch_size': 25, 'num_epochs': 50, 'patience': 5, 'num_batches': 100, 'd_lr': 0.0001, 'e_lr': 0.001, 'timesteps': 10000, 'prob_statio': 0.98, 'task_sequence': None, 'n_steps_per_task': 1, 'verbose': False, 'model_config': 'Config/debug.yaml', 'deeper': 0, 'wandb_group': 'ACL_0.98', 'device': 'cpu'}
2021-09-13 19:20:04,246 INFO    MainThread:86049 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:20:04,246 INFO    MainThread:86049 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:20:04,246 INFO    MainThread:86049 [wandb_init.py:_log_setup():342] Logging user logs to /Users/wenxuanzhang/Desktop/ACL_OSAKA/wandb/run-20210913_192004-2alxb62x/logs/debug.log
2021-09-13 19:20:04,246 INFO    MainThread:86049 [wandb_init.py:_log_setup():343] Logging internal logs to /Users/wenxuanzhang/Desktop/ACL_OSAKA/wandb/run-20210913_192004-2alxb62x/logs/debug-internal.log
2021-09-13 19:20:04,247 INFO    MainThread:86049 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fe01868e748>
2021-09-13 19:20:04,247 INFO    MainThread:86049 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:20:04,247 INFO    MainThread:86049 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:20:04,247 INFO    MainThread:86049 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 2qft0qc8
2021-09-13 19:20:04,247 INFO    MainThread:86049 [wandb_run.py:finish():1271] finishing run wxzhang0210/uncategorized/2qft0qc8
